spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: create
  datasource:
    #    driver-class-name: org.h2.Driver
    #    url: jdbc:h2:tcp://localhost/~/test
    #    #    url: jdbc:h2:tcp://localhost/~/h2/spring
    #    username: sa
    #    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db?useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234

logging:
  level:
    root: ERROR